# This file was generated by GoReleaser. DO NOT EDIT.
cask "saucer" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "1ac1feee93f730b506ad4e6d6e5823308808a568b14eae8e63444f4907f1d402"
      url "https://github.com/ldreux/saucer/releases/download/v#{version}/saucer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea9376772b9fbacfea871ffc4a19456af8c3601f05c8390bfd0912ff3821ce9a"
      url "https://github.com/ldreux/saucer/releases/download/v#{version}/saucer_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "saucer"
  desc "Terminal Pomodoro / countdown / timer / clock app"
  homepage "https://github.com/ldreux/saucer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saucer"

  # No zap stanza required

end
