# This file was generated by GoReleaser. DO NOT EDIT.
cask "saucer" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "695004b0a51050eeccd4f62c8c7fa0903e33fd74a0b8ff3fe133fa89ff9e6290"
      url "https://github.com/ldreux/saucer/releases/download/v#{version}/saucer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f65dce2b0821eca6773c81af63b26d20d76e53e21526bcba400f565cb3067c4e"
      url "https://github.com/ldreux/saucer/releases/download/v#{version}/saucer_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "saucer"
  desc "Terminal Pomodoro / countdown / timer / clock app"
  homepage "https://github.com/ldreux/saucer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saucer"

  # No zap stanza required

end
