# This file was generated by GoReleaser. DO NOT EDIT.
cask "saucer" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "2baa497bb955dad6af79de0878001206f630c97fb012b0706366ada713eda46e"
      url "https://github.com/ldreux/saucer/releases/download/v#{version}/saucer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9d83616f983bcfa62405ad31ff8e022f66bd18b4fa8ac26d05ab3bf3ba2ab8e0"
      url "https://github.com/ldreux/saucer/releases/download/v#{version}/saucer_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "saucer"
  desc "Terminal Pomodoro / countdown / timer / clock app"
  homepage "https://github.com/ldreux/saucer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saucer"

  # No zap stanza required

end
